### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by Crell** [Crell/enum-comparison#46]
Right now, serialization is either a loophole around === working, or a fatal.  Unless we can be certain how it's going to behave, we may want to just forbid it for now, at least until we figure out how it should work better.

I don't think `unserialize(serialize(Suit::Clubs));` is ever going to really play nice without a ton of work, so better to not have it half-work.

**Comment by dbalabka** [comment]
@Crell sometime ago I've reviewed this problem in the context of Enum implementation in pure PHP and singleton serialization in general:
https://github.com/dbalabka/php-enumeration#serialization
In result, I've decided to restrict serialization because it is impossible to handle it in PHP. Still, there is a workaround which implementation you can find here:
https://github.com/dbalabka/php-enumeration/blob/cc5dea147a9b9f526704952c6b0957ad5d890ed8/examples/serialization_php74.php#L68
Idea behind this workaround is that you always serialize enum in the scope of some object which can control enum reference serialization using `__serialize` and `__unserialize` methods.

IMO there should be built-in PHP functionality which gives possibility to serialize any singleton. I've explored how Java [handles](https://stackoverflow.com/questions/15521309/is-custom-enum-serializable-too/15522276#15522276) Enums serialization and it seems that we need something similar to Java's [readResolve()](https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html) method.

**Comment by iluuu1994** [comment]
Disallowing enums in serialize means, whatever object you're serializing must not contain and single enum. That seems pretty limiting. I'll see if we can make this work.

**Comment by iluuu1994** [comment]
We now have serialization.
